# Generated by Django 4.1.7 on 2023-03-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='score_description',
            field=models.CharField(default='Sin calificar', max_length=255),
        ),
    ]
